<#
.SYNOPSIS
    Builds WiClip: publishes the app and packages it into an MSI.

.DESCRIPTION
    Run on Windows. Requirements:
      * .NET SDK 8.0+   https://dotnet.microsoft.com/download
      * WiX Toolset 5   dotnet tool install --global wix --version 5.0.2

.EXAMPLE
    .\build.ps1
    .\build.ps1 -Version 1.2.0 -Culture en-US
    .\build.ps1 -SkipMsi          # executable only, no installer
#>
[CmdletBinding()]
param(
    [string]$Version = "1.1.0",
    [ValidateSet("x64", "x86", "arm64")]
    [string]$Arch = "x64",
    [string]$Configuration = "Release",
    [string]$Culture = "ru-RU",
    [switch]$SkipMsi
)

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$project = Join-Path $root "src\WiClip\WiClip.csproj"
$publishDir = Join-Path $root "publish\$Arch"
$installerDir = Join-Path $root "installer"
$distDir = Join-Path $root "dist"
$generatedWxs = Join-Path $installerDir "Files.generated.wxs"

# MSI requires a four-part version a.b.c.d
$msiVersion = if ($Version -match '^\d+\.\d+\.\d+\.\d+$') { $Version } else { "$Version.0" }

function Write-Step($text) { Write-Host "`n==> $text" -ForegroundColor Cyan }

# ---------------------------------------------------------------- publish ---
Write-Step "Publishing the application ($Arch, $Configuration)"

# A running instance locks its own files and breaks the publish step
$running = Get-Process -Name WiClip -ErrorAction SilentlyContinue
if ($running) {
    Write-Host "Closing running WiClip (PID $($running.Id -join ', '))..."
    $running | Stop-Process -Force
    Start-Sleep -Milliseconds 500
}

if (Test-Path $publishDir) { Remove-Item $publishDir -Recurse -Force }

dotnet publish $project `
    -c $Configuration `
    -r "win-$Arch" `
    --self-contained true `
    -p:Version=$Version `
    -p:FileVersion=$msiVersion `
    -p:AssemblyVersion=$msiVersion `
    -o $publishDir
if ($LASTEXITCODE -ne 0) { throw "dotnet publish failed." }

# Debug symbols do not belong in the installer
Get-ChildItem $publishDir -Filter *.pdb -Recurse | Remove-Item -Force

$exe = Join-Path $publishDir "WiClip.exe"
if (-not (Test-Path $exe)) { throw "WiClip.exe not found in $publishDir" }

$fileCount = (Get-ChildItem $publishDir -Recurse -File).Count
$sizeMb = [math]::Round(((Get-ChildItem $publishDir -Recurse -File | Measure-Object Length -Sum).Sum / 1MB), 1)
Write-Host "Done: $fileCount files, $sizeMb MB -> $publishDir"

if ($SkipMsi) {
    Write-Host "`nMSI skipped (-SkipMsi). Application: $exe" -ForegroundColor Green
    return
}

# ----------------------------------------------------- generate file list ---
Write-Step "Generating Files.generated.wxs"

$sb = [System.Text.StringBuilder]::new()
$null = $sb.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
$null = $sb.AppendLine('<!-- Generated by build.ps1. Manual edits will be overwritten. -->')
$null = $sb.AppendLine('<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">')
$null = $sb.AppendLine('  <Fragment>')

# Directories: mirror the publish subfolders inside APPLICATIONFOLDER
$dirIds = @{ "" = "APPLICATIONFOLDER" }
$subDirs = Get-ChildItem $publishDir -Recurse -Directory | Sort-Object FullName
if ($subDirs) {
    $null = $sb.AppendLine('    <DirectoryRef Id="APPLICATIONFOLDER">')
    $open = New-Object System.Collections.Stack
    foreach ($dir in $subDirs) {
        $rel = $dir.FullName.Substring($publishDir.Length).TrimStart('\')
        $id = "dir_" + ($rel -replace '[^A-Za-z0-9_]', '_')
        $dirIds[$rel] = $id

        # Close directories that are no longer ancestors of the current one
        while ($open.Count -gt 0 -and -not $rel.StartsWith($open.Peek() + '\')) {
            $null = $open.Pop()
            $null = $sb.AppendLine(('      ' + ('  ' * $open.Count) + '</Directory>'))
        }
        $indent = '      ' + ('  ' * $open.Count)
        $null = $sb.AppendLine("$indent<Directory Id=`"$id`" Name=`"$($dir.Name)`">")
        $open.Push($rel)
    }
    while ($open.Count -gt 0) {
        $null = $open.Pop()
        $null = $sb.AppendLine(('      ' + ('  ' * $open.Count) + '</Directory>'))
    }
    $null = $sb.AppendLine('    </DirectoryRef>')
}

# One file per component - MSI wants a single keypath per component
$null = $sb.AppendLine('    <ComponentGroup Id="AppFiles">')
$index = 0
foreach ($file in (Get-ChildItem $publishDir -Recurse -File | Sort-Object FullName)) {
    $rel = $file.FullName.Substring($publishDir.Length).TrimStart('\')
    $relDir = Split-Path $rel -Parent
    $dirId = $dirIds[$relDir]
    if (-not $dirId) { throw "No directory mapped for $rel" }

    # The main executable keeps a fixed Id - CustomAction in WiClip.wxs refers to it
    if ($rel -eq "WiClip.exe") {
        $fileId = "WiClipExe"
        $compId = "cmp_WiClipExe"
    }
    else {
        $index++
        $fileId = "fil_$index"
        $compId = "cmp_$index"
    }

    $source = [System.Security.SecurityElement]::Escape($file.FullName)
    $null = $sb.AppendLine("      <Component Id=`"$compId`" Directory=`"$dirId`">")
    $null = $sb.AppendLine("        <File Id=`"$fileId`" Source=`"$source`" KeyPath=`"yes`" />")
    $null = $sb.AppendLine('      </Component>')
}
$null = $sb.AppendLine('    </ComponentGroup>')
$null = $sb.AppendLine('  </Fragment>')
$null = $sb.AppendLine('</Wix>')

Set-Content -Path $generatedWxs -Value $sb.ToString() -Encoding UTF8
Write-Host "Written: $generatedWxs"

# -------------------------------------------------------------------- msi ---
Write-Step "Building the MSI"

if (-not (Get-Command wix -ErrorAction SilentlyContinue)) {
    throw "WiX not found. Install it: dotnet tool install --global wix --version 5.0.2"
}

# Extension versions must match the wix tool version (4/5/6/7 all differ)
$wixVersion = $null
$raw = (& wix --version) 2>$null
if ("$raw" -match '(\d+\.\d+\.\d+)') { $wixVersion = $Matches[1] }
Write-Host "WiX version $(if ($wixVersion) { $wixVersion } else { 'unknown' })"

# WiX 6 and newer require accepting the Open Source Maintenance Fee EULA (error WIX7015)
if ($wixVersion -and [int]($wixVersion.Split('.')[0]) -ge 6) {
    Write-Warning @"
WiX $wixVersion is installed. Since version 6 it requires accepting the OSMF EULA
(https://wixtoolset.org/osmf/) and fails with WIX7015 otherwise.
The simplest fix is to go back to the free version 5:
    dotnet tool uninstall --global wix
    dotnet tool install --global wix --version 5.0.2
"@
}

foreach ($ext in @("WixToolset.UI.wixext", "WixToolset.Util.wixext")) {
    $spec = if ($wixVersion) { "$ext/$wixVersion" } else { $ext }
    Write-Host "Extension: $spec"
    & wix extension add -g $spec
    if ($LASTEXITCODE -ne 0 -and $wixVersion) {
        # An exact version match may be missing on NuGet - fall back to the latest
        & wix extension add -g $ext
    }
    if ($LASTEXITCODE -ne 0) {
        throw "Could not add extension $ext. Check internet access (NuGet) " +
              "and run it manually: wix extension add -g $spec"
    }
}

New-Item -ItemType Directory -Force -Path $distDir | Out-Null
$msi = Join-Path $distDir "WiClip-$Version-$Arch.msi"

# Installer strings live in installer\*.wxl; the LCID must match the chosen culture
$lang = switch ($Culture) {
    "ru-RU" { 1049 }
    "en-US" { 1033 }
    default { throw "Unsupported culture '$Culture'. Add a .wxl file in installer\ and map its LCID here." }
}

wix build `
    (Join-Path $installerDir "WiClip.wxs") `
    $generatedWxs `
    -arch $Arch `
    -culture $Culture `
    -loc (Join-Path $installerDir "en-us.wxl") `
    -loc (Join-Path $installerDir "ru-ru.wxl") `
    -ext WixToolset.UI.wixext `
    -ext WixToolset.Util.wixext `
    -d Version=$msiVersion `
    -d Lang=$lang `
    -d PublishDir=$publishDir `
    -d InstallerDir=$installerDir `
    -o $msi
if ($LASTEXITCODE -ne 0) { throw "wix build failed." }

$msiMb = [math]::Round((Get-Item $msi).Length / 1MB, 1)
Write-Host "`nDone: $msi ($msiMb MB)" -ForegroundColor Green
Write-Host "Silent install:  msiexec /i `"$msi`" /qn" -ForegroundColor DarkGray
